### ISSUE TITLE
PEN-SOLDER V7 possibly not compatible.

### ISSUE THREAD

**Issue by Nomad990** [spezifisch/T12PenSolder#1]
I ordered a same style solder pen off of aliexpress and the board says v7 instead of v3 upon flashing the firmware it shows way less info than intended on the oled screen.
![20240121_193527](https://github.com/spezifisch/T12PenSolder/assets/155561246/4c925b1a-5d19-44cf-b7b5-aa76e30bdff6)

**Comment by spezifisch** [comment]
Do you have a dump of the original firmware? Perhaps the OLED display initialization is different from V3 and could be adapted.

**Comment by Nomad990** [comment]
I can upload one in a couple days I didn't notice until I had already tried flashing the v3 firmware but I have a stock iron on the way.

**Comment by Mafoto47** [comment]
Hi! Here is the V7 original firmware I have just dump. 
[Pen_Solder_V7_ori.zip](https://github.com/spezifisch/T12PenSolder/files/14152262/Pen_Solder_V7_ori.zip)
I have the same result as Nomad990 with the V3 modded Firwware.
Thanks for your work!!

**Comment by Gobracket** [comment]
Hi, great job!
Does this finally fixed for v7 board? Wondering if only impact the display or other feature as well?

**Comment by Gobracket** [comment]
This is the solution for v7 board:

Add code below
```
  u8g2.sendF("ca", 0x0a8, 0x02f); 
``` 
to https://github.com/spezifisch/T12PenSolder/blob/11f69184440a310940f4706372f33aca9d6d7e08/firmware/src/main.cpp#L56

Then power off the board (MUST!). The display will be fixed when you turn it back on.

**Comment by Zalevskiypasha** [comment]
Hello
Can someone post a final build for v7?
I want to update, but I can’t assemble the firmware

**Comment by Zalevskiypasha** [comment]
hello.
Thank you for the goog job. It`s amazing/
Before your firmware i tried to upload .bin, and it was successfull
But now i have a trouble. Can you, please say, whay i did wrong?
1. Install VSC
2. Instal Platformio, CC+ 
3. Connect iron with ST-LINK v2 dongle
4. in Platformio i had opened this project, and pressed upload
5. after, i had this answer:
Processing t12f030 (platform: ststm32; board: t12f030; framework: arduino)
--------------------------------------------------------------------------------------------------------------------------------------------Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/ststm32/t12f030.html
PLATFORM: ST STM32 (17.2.0) > T12 F030 Soldering Iron
HARDWARE: STM32F030F6P6 48MHz, 4KB RAM, 32KB Flash
DEBUG: Current (stlink) On-board (stlink) External (blackmagic, cmsis-dap, jlink)
PACKAGES:
 - framework-arduinoststm32 @ 4.20701.0 (2.7.1)
 - framework-cmsis @ 2.50900.0 (5.9.0)
 - toolchain-gccarmnoneeabi @ 1.120301.0 (12.3.1)
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 13 compatible libraries
Scanning dependencies...
Dependency Graph
|-- U8g2 @ 2.35.2
Building in release mode
Compiling .pio\build\t12f030\FrameworkArduinoVariant\PeripheralPins.c.o
Compiling .pio\build\t12f030\FrameworkArduinoVariant\generic_clock.c.o
Compiling .pio\build\t12f030\FrameworkArduinoVariant\variant_T12F030.cpp.o
arm-none-eabi-gcc: fatal error: cannot execute 'c:/users/zalpa/.platformio/packages/toolchain-gccarmnoneeabi@1.70201.0/bin/../libexec/gcc/arm-none-eabi/12.3.1/cc1.exe': CreateProcess: No such file or directory
compilation terminated.
Compiling .pio\build\t12f030\SrcWrapper\src\HAL\stm32yyxx_hal.c.o
arm-none-eabi-gcc: fatal error: cannot execute 'c:/users/zalpa/.platformio/packages/toolchain-gccarmnoneeabi@1.70201.0/bin/../libexec/gcc/arm-none-eabi/12.3.1/cc1.exe': CreateProcess: No such file or directory
compilation terminated.
*** [.pio\build\t12f030\FrameworkArduinoVariant\PeripheralPins.c.o] Error 1
*** [.pio\build\t12f030\FrameworkArduinoVariant\generic_clock.c.o] Error 1
arm-none-eabi-g++: fatal error: cannot execute 'c:/users/zalpa/.platformio/packages/toolchain-gccarmnoneeabi@1.70201.0/bin/../libexec/gcc/arm-none-eabi/12.3.1/cc1plus.exe': CreateProcess: No such file or directory
compilation terminated.
*** [.pio\build\t12f030\FrameworkArduinoVariant\variant_T12F030.cpp.o] Error 1
arm-none-eabi-gcc: fatal error: cannot execute 'c:/users/zalpa/.platformio/packages/toolchain-gccarmnoneeabi@1.70201.0/bin/../libexec/gcc/arm-none-eabi/12.3.1/cc1.exe': CreateProcess: No such file or directory
compilation terminated.
*** [.pio\build\t12f030\SrcWrapper\src\HAL\stm32yyxx_hal.c.o] Error 1
========================================================================================== [FAILED] Took 3.06 seconds

**Comment by Zalevskiypasha** [comment]
For all, who have v7
[V7.zip](https://github.com/spezifisch/T12PenSolder/files/14891503/V7.zip)

**Comment by spezifisch** [comment]
I finally got around to test and merge this.
The different initialization is not compatible with V3 (gives me a garbled screen) so I added a build option to switch between V3 and V7, see https://github.com/spezifisch/T12PenSolder/blob/6f2c2afc952d80434b5463d7841688dab391555d/README.md#pen-solder-v7.

Thanks to you all!
